[2025-06-14 07:52:44 +0200] [4139800] [INFO] Starting gunicorn 23.0.0
[2025-06-14 07:52:44 +0200] [4139800] [INFO] Listening at: http://127.0.0.1:8000 (4139800)
[2025-06-14 07:52:44 +0200] [4139800] [INFO] Using worker: sync
[2025-06-14 07:52:44 +0200] [4139841] [INFO] Booting worker with pid: 4139841
[2025-06-14 07:52:44 +0200] [4139841] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
    ~~~~~~~~~~~~~~^^
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2025-06-14 07:52:44 +0200] [4139841] [INFO] Worker exiting (pid: 4139841)
[2025-06-14 07:52:44 +0200] [4139800] [ERROR] Worker (pid:4139841) exited with code 3
[2025-06-14 07:52:44 +0200] [4139800] [ERROR] Shutting down: Master
[2025-06-14 07:52:44 +0200] [4139800] [ERROR] Reason: Worker failed to boot.
